CREATE TABLE fit2104_a2.COURSE 
(
    id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(64) NOT NULL, 
    price INT NOT NULL,
    category_id INT NOT NULL,
    PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE fit2104_a2.COURSE_IMAGE
(
    id INT NOT NULL AUTO_INCREMENT, 
    course_id INT NOT NULL,
    filePath VARCHAR(64) NOT NULL, 
    PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE fit2104_a2.CATEGORY
(
    id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(64) NOT NULL, 
    PRIMARY KEY (id)
) ENGINE = InnoDB;

ALTER TABLE `COURSE` ADD FOREIGN KEY (`category_id`) REFERENCES `CATEGORY`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `COURSE_IMAGE` ADD FOREIGN KEY (`course_id`) REFERENCES `COURSE`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;